server:
  port: 9090
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:9001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'